// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1674759526);
user_pref("app.update.lastUpdateTime.region-update-timer", 1674759166);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1674759286);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1674759406);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1674759766);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1674759646);
user_pref("browser.region.update.updated", 1674759167);
user_pref("browser.search.region", "US");
user_pref("calendar.list.sortOrder", "2998aa5f-153c-447f-8b08-3c6b6144cee9");
user_pref("calendar.registry.2998aa5f-153c-447f-8b08-3c6b6144cee9.calendar-main-default", true);
user_pref("calendar.registry.2998aa5f-153c-447f-8b08-3c6b6144cee9.calendar-main-in-composite", true);
user_pref("calendar.registry.2998aa5f-153c-447f-8b08-3c6b6144cee9.disabled", true);
user_pref("calendar.registry.2998aa5f-153c-447f-8b08-3c6b6144cee9.name", "Home");
user_pref("calendar.registry.2998aa5f-153c-447f-8b08-3c6b6144cee9.type", "storage");
user_pref("calendar.registry.2998aa5f-153c-447f-8b08-3c6b6144cee9.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "America/New_York");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1674154617522");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1675361548);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20221101185644");
user_pref("extensions.lastAppVersion", "102.4.2");
user_pref("extensions.lastPlatformVersion", "102.4.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"2cdc51df-9669-423d-9a61-193bf29dc876\",\"google@search.mozilla.org\":\"9f5ee845-719e-47e7-a909-d166fd600549\",\"ddg@search.mozilla.org\":\"124d1a4e-de7f-42fa-88e1-15e390efee9c\",\"amazondotcom@search.mozilla.org\":\"da65b647-fc19-4a89-94b5-d33ac6c071ae\",\"wikipedia@search.mozilla.org\":\"1afcfc43-c2f2-48d6-8612-7a6807a8c253\",\"bing@search.mozilla.org\":\"df7f2bbc-2845-4a6f-8d51-f0a7cd1c234c\"}");
user_pref("idle.lastDailyNotification", 1674759366);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "23a574c2-3416-4426-9413-4fbcf5dd862");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.4.2");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("places.database.lastMaintenance", 1674759366);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -17489);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1674776895);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1674776895);
user_pref("services.settings.thunderbird.search-config.last_check", 1674776895);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1674776895);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.telemetry.cachedClientID", "0b73c239-8388-4452-9f85-330ce99f0d1e");
user_pref("toolkit.telemetry.previousBuildID", "20221101185644");
